packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - "@google/genai"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - bcrypt
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs