export const EVENTS = {
  APPLICATION_CREATED: "APPLICATION_CREATED",
  JOB_ALERT_CREATED: "JOB_ALERT_CREATED",
  RESUME_UPLOADED_EVENT: "resume.uploaded",
  JOB_CREATED_EVENT: "job.created",
  CANDIDATE_STATUS_UPDATED: "candidate.status.updated",
  APPLICATION_STATUS_UPDATED: "APPLICATION_STATUS_UPDATED",
};
